steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/my-spring-boot-app:latest'
    - '.'

# Step 2: Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/spring-boot-deployment'
    - 'spring-boot-container=gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a' 
    - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
    
options:
  logging: CLOUD_LOGGING_ONLY