steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest', '--build-arg=JAR_FILE=my-spring-boot-app.jar','.']
    id: 'Build Docker Image'
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest']
    id: 'Push Docker Image'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/spring-boot-deployment'
      - 'spring-boot-container=gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a' 
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'