steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest'
    - '.'

# Step 2: Push the Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest'

# Step 3: Deploy to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/spring-boot-deployment'
    - 'spring-boot-container=gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a' 
    - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
