steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest'

# Deploy to Kubernetes    
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/deployment-1'
    - 'spring-boot-container=gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1' 
    - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'
    
options:
  logging: CLOUD_LOGGING_ONLY