apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      serviceAccountName: bf-cloud-sa@primordial-veld-442819-k2.iam.gserviceaccount.com
      containers:
      - name: spring-boot-container
        image: gcr.io/primordial-veld-442819-k2/my-spring-boot-app:latest
        ports:
        - containerPort: 8080