apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-spring-boot-app
  template:
    metadata:
      labels:
        app: my-spring-boot-app
    spec:
      containers:
      - name: spring-boot-container
        image: gcr.io/primordial-veld-442819-k2/my-spring-boot-app:$COMMIT_SHA
        ports:
        - containerPort: 8080