apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-0.0.1-SNAPSHOT
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-0.0.1-SNAPSHOT
  template:
    metadata:
      labels:
        app: gcp-0.0.1-SNAPSHOT
    spec:
      containers:
        - name: gcp-0.0.1-SNAPSHOT
          image: gcr.io/$PROJECT_ID/gcp-0.0.1-SNAPSHOT:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-0.0.1-SNAPSHOT
spec:
  type: LoadBalancer
  selector:
    app: gcp-0.0.1-SNAPSHOT
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080